<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:game itemname="游戏名字" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="255" page="">
</field:game>
<field:fenlei itemname="游戏类型" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fenlei>
<field:ticai itemname="游戏题材" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:ticai>
<field:size itemname="游戏大小" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:size>
<field:rebate itemname="游戏优惠标签【icon使用】" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:rebate>
<field:fuli itemname="游戏福利①】" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fuli>
<field:fuli2 itemname="游戏福利②】" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:fuli2>
<field:fuli3 itemname="游戏福利③】" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fuli3>
<field:fuli4 itemname="游戏福利④】" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fuli4>
<field:jt01 itemname="游戏截图①" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jt01>
<field:jt02 itemname="游戏截图②" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jt02>
<field:jt03 itemname="游戏截图③" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jt03>
<field:jt04 itemname="游戏截图④" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jt04>
<field:jt05 itemname="游戏截图⑤" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jt05>
